##
#	Auteur: Genevieve Pelletier-McDuff, Charles De Lafontaine, Matis Gregoire, Fanilotiana Guy et Ismail Essid
# 
#	Description: Permet de compiler un ou plusieurs fichiers .c/.cpp  .cpp en .elf, .map, .o, et .hex afin de voir le resultat de notre
#				 code dans un circuit sur SimulIDE ou de l'installer directement sur la carte mere grace a avrdude.
#
#	Mise en garde: La librairie doit etre prealablement creee avant d'utiliser ce Makefile.
##

# Nom du projet
PROJECTNAME=projet

# Fichiers sources
PRJSRC=projet.cpp

# Inclusions additionnelles
INC=../lib

# Librairies à lier
LIBS=projet

include ../lib/Makefile_commun/Makefile_impl
